apiVersion: v1
kind: Secret
metadata:
  name: nzbget-secrets
  namespace: media
  labels:
    app: nzbget
type: Opaque
data:
  username: "YWRtaW4="
  password: "cm9iZXJ0amY="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nzbget-config
  namespace: media
  labels:
    app: nzbget
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/London"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget-deployment
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
      namespace: media
    spec:
      containers:
        - name: nzbget
          image: linuxserver/nzbget:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
              ephemeral-storage: "8Gi"
            limits:
              memory: "16Gi"
              cpu: "2"
              ephemeral-storage: "32Gi"
          readinessProbe:
            httpGet:
              port: 6789
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: nzbget-http
              containerPort: 6789
          envFrom:
            - configMapRef:
                name: nzbget-config
          env:
            - name: NZBGET_USER
              valueFrom:
                secretKeyRef:
                  name: nzbget-secrets
                  key: username
            - name: NZBGET_PASS
              valueFrom:
                secretKeyRef:
                  name: nzbget-secrets
                  key: password
          volumeMounts:
            - mountPath: "/config"
              subPath: "config"
              name: nzbget-data
            - mountPath: "/downloads"
              subPath: "downloads"
              name: nzbget-data
            - mountPath: "/media"
              name: nzbget-nfs-media
              
      volumes:
        - name: nzbget-data
          persistentVolumeClaim:
            claimName: nzbget-data-pvc
        - name: nzbget-nfs-media
          nfs:
            path: /volume1/media/
            server: deepthought.lan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-data-pvc
  namespace: media
  labels:
    app: nzbget
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget-tcp
  namespace: media
  labels:
    app: nzbget
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.212
  externalTrafficPolicy: Local
  ports:
    - name: nzbget-http
      port: 6789
      protocol: TCP
      targetPort: nzbget-http  
  selector:
    app: nzbget