apiVersion: v1
kind: Secret
metadata:
  name: nzbget-passwd
  namespace: media
  labels:
    app: nzbget
type: Opaque
data:
  username: "YWRtaW4="
  password: "cm9iZXJ0amY="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nzbget-config
  namespace: media
  labels:
    app: nzbget
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Edmonton"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget-deployment
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
      namespace: media
    spec:
      containers:
        - name: nzbget
          image: linuxserver/nzbget:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
              ephemeral-storage: "8Gi"
            limits:
              memory: "16Gi"
              cpu: "2"
              ephemeral-storage: "32Gi"
          envFrom:
            - configMapRef:
                name: nzbget-config
          env:
            - name: NZBGET_USER
              valueFrom:
                secretKeyRef:
                  name: nzbget-passwd
                  key: username
            - name: NZBGET_PASS
              valueFrom:
                secretKeyRef:
                  name: nzbget-passwd
                  key: password
          ports:
            - name: web-admin
              protocol: TCP
              containerPort: 6789
          readinessProbe:
            tcpSocket:
              port: web-admin
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: web-admin
            initialDelaySeconds: 15
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: "/config"
              name: nzbget-data
            - mountPath: "/downloads"
              name: nzbget-downloads
      volumes:
        - name: nzbget-data
          persistentVolumeClaim:
            claimName: nzbget-data-pvc
        - name: nzbget-downloads
          persistentVolumeClaim:
            claimName: nzbget-downloads-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-data-pvc
  namespace: media
  labels:
    app: nzbget
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget-tcp
  namespace: media
  labels:
    app: nzbget
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.203
  externalTrafficPolicy: Local
  ports:
    - name: web-admin
      protocol: TCP
      port: 6789
      targetPort: web-admin
  selector:
    app: nzbget