apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-config
  namespace: media
  labels:
    app: radarr
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Edmonton"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-deployment
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
      namespace: media
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 4Gi
            cpu: 1500m
            ephemeral-storage: 4Gi
        envFrom:
          - configMapRef:
              name: radarr-config
        ports:
          - name: http-web
            protocol: TCP
            containerPort: 7878
        volumeMounts:
          - mountPath: "/config"
            name: radarr-data
          - mountPath: "/downloads"
            name: shared-downloads
          - mountPath: "/movies"
            name: shared-media
      volumes:
        - name: radarr-data
          persistentVolumeClaim:
            claimName: radarr-data-pvc
        - name: shared-downloads
          persistentVolumeClaim:
            claimName: shared-downloads-pvc
        - name: shared-media
          nfs:
            server: deepthought.lan
            path: /volume1/media/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data-pvc
  namespace: media
  labels:
    app: radarr
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-tcp
  namespace: media
  labels:
    app: radarr
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.205
  externalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-web
    - name: http-web
      protocol: TCP
      port: 7878
      targetPort: http-web
  selector:
    app: radarr