apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-media-pv
  namespace: media
  labels:
    app: all
spec:
  capacity:
    storage: 6Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/media/
    server: 192.168.1.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media-pvc
  namespace: media
  labels:
    app: all
spec:
  resources:
    requests:
      storage: 6Ti
  storageClassName: nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
