apiVersion: v1
kind: PersistentVolume
metadata:
  name: nzbget-downloads-pv
  namespace: media  
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /opt/nzbget/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-downloads-pvc
  namespace: media  
spec:  
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeName: nzbget-downloads-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
  namespace: media  
spec:
  capacity:
    storage: 6Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  local:
    server: deepthought.lan
    path: /volume1/media/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: media  
spec:  
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 6Ti
  storageClassName: nfs
  volumeName: media-nfs-pv