apiVersion: v1
kind: ConfigMap
metadata:
  name: nzbget-config
  namespace: media
  labels:
    app: nzbget
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Edmonton"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-deployment
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
      namespace: media
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: http-web
            protocol: TCP
            containerPort: 8989
        readinessProbe:
          httpGet:
            port: http-web
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            port: http-web
          initialDelaySeconds: 15
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: "/config"
            name: sonarr-data
          - mountPath: "/downloads"
            name: shared-downloads
          - mountPath: "/media"
            name: shared-media
      volumes:
        - name: sonarr-data
          persistentVolumeClaim:
            claimName: sonarr-data-pvc
        - name: shared-downloads
          persistentVolumeClaim:
            claimName: shared-downloads-pvc
        - name: shared-media
          nfs:
            server: deepthought.lan
            path: /volume1/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data-pvc
  namespace: media
  labels:
    app: sonarr
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-tcp
  namespace: media
  labels:
    app: sonarr
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.204
  externalTrafficPolicy: Local
  ports:
    - name: http-web
      protocol: TCP
      port: 8989
      targetPort: http-web
  selector:
    app: sonarr