apiVersion: v1
kind: ConfigMap
metadata:
  name: kavita-config
  namespace: media
  labels:
    app: kavita
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Edmonton"
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita-deployment
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
      namespace: media
    spec:
      restartPolicy: Always
      containers:
        - name: kavita
          image: linuxserver/kavita:latest
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 1000m
              ephemeral-storage: 10Gi
          envFrom:
            - configMapRef:
                name: kavita-config
          ports:
            - name: http-web
              protocol: TCP
              containerPort: 5000
          readinessProbe:
            tcpSocket:
              port: http-web
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http-web
            initialDelaySeconds: 15
            periodSeconds: 5
          volumeMounts:
            - mountPath: "/config"
              name: kavita-data
            - mountPath: "/mnt/media"
              name: shared-media
      volumes:
        - name: kavita-data
          iscsi:
            targetPortal: "192.168.1.2"
            iqn: "iqn.2025-06.com.synology:deepthought.kavita-1"
            lun: 1
            fsType: ext4
            readOnly: false
        - name: shared-media
          persistentVolumeClaim:
            claimName: shared-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kavita-tcp
  namespace: media
  labels:
    app: kavita
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.206
  externalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-web
    - name: http-web
      protocol: TCP
      port: 5000
      targetPort: http-web
  selector:
    app: kavita
