apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-config
  namespace: media
  labels:
    app: plex
data:
  TZ: "America/Edmonton"
  ADVERTISE_IP: "http://192.168.1.202:32400/"
  ALLOWED_NETWORKS: "192.168.1.0/24"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
      namespace: media
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
              ephemeral-storage: "2Gi"
            limits:
              memory: "32Gi"
              cpu: "4"
              ephemeral-storage: "4Gi"
          envFrom:
            - configMapRef:
                name: plex-config
          env:
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-claim-token
                  key: token
          # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
          ports:
            - name: pms
              protocol: TCP
              containerPort: 32400
            - name: dnla-udp
              protocol: UDP
              containerPort: 1900
            - name: dnla-tcp
              protocol: TCP
              containerPort: 32469
            - name: plex-ht
              protocol: TCP
              containerPort: 3005
            - name: bonjour
              protocol: TCP
              containerPort: 5353
            - name: plex-roku
              protocol: TCP
              containerPort: 8324
            - name: gdm32410
              protocol: UDP
              containerPort: 32410
            - name: gdm32412
              protocol: UDP
              containerPort: 32412
            - name: gdm32413
              protocol: UDP
              containerPort: 32413
            - name: gdm32414
              protocol: UDP
              containerPort: 32414
          startupProbe:
            httpGet:
              path: /identity
              port: pms
            failureThreshold: 30    # 10s x 30 = 5min
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /identity
              port: pms
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /identity
              port: pms
            initialDelaySeconds: 15
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: "/config"
              name: plex-data
            - mountPath: "/transcode"
              name: plex-transcode
            - mountPath: "/media"
              name: shared-media
      volumes:
        - name: plex-data
          persistentVolumeClaim:
            claimName: plex-data-pvc
        - name: plex-transcode
          emptyDir:
            sizeLimit: 30Gi
        - name: shared-media
          persistentVolumeClaim:
            claimName: shared-media-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-pvc
  namespace: media
  labels:
    app: plex
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: Service
metadata:
  name: plex-udp
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: "plex-svc"
  labels:
    app: plex
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.202
  externalTrafficPolicy: Local
  ports:
    - name: dnla-udp
      protocol: UDP
      port: 1900
      targetPort: dnla-udp
    - name: gdm32410
      protocol: UDP
      port: 32410
      targetPort: gdm32410
    - name: gdm32412
      protocol: UDP
      port: 32412
      targetPort: gdm32412
    - name: gdm32413
      protocol: UDP
      port: 32413
      targetPort: gdm32413
    - name: gdm32414
      protocol: UDP
      port: 32414
      targetPort: gdm32414
  selector:
    app: plex
---
apiVersion: v1
kind: Service
metadata:
  name: plex-tcp
  namespace: media
  annotations:
      metallb.universe.tf/allow-shared-ip: "plex-svc"
  labels:
    app: plex
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.202
  externalTrafficPolicy: Local
  ports:
    - name: pms
      protocol: TCP
      port: 32400
      targetPort: pms
    - name: plex-ht
      protocol: TCP
      port: 3005
      targetPort: plex-ht
    - name: bonjour
      protocol: TCP
      port: 5353
      targetPort: bonjour
    - name: plex-roku
      protocol: TCP
      port: 8324
      targetPort: plex-roku
    - name: dnla-tcp
      protocol: TCP
      port: 32469
      targetPort: dnla-tcp
  selector:
    app: plex