apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-config
  namespace: unifi
  labels:
    app: unifi-controller
data:
  TZ: "America/Edmonton"
  PGID: "1000"
  GUID: "1000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller-deployment
  namespace: unifi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
      namespace: unifi
    spec:
      containers:
        - name: unifi-controller
          image: linuxserver/unifi-controller
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
              ephemeral-storage: "500Mi"
            limits:
              memory: "4Gi"
              cpu: "2"
              ephemeral-storage: "1Gi"
          envFrom:
            - configMapRef:
                name: unifi-config
          # https://help.ui.com/hc/en-us/articles/218506997-UniFi-Network-Required-Ports-Reference
          ports:            
            - name: dns
              containerPort: 53
            - name: web-admin
              containerPort: 8443
              protocol: TCP
            - name: api
              containerPort: 8080
              protocol: TCP
            - name: guest-https
              containerPort: 8843
              protocol: TCP
            - name: guest-http
              containerPort: 8880
              protocol: TCP
            - name: speed-test
              containerPort: 6789
              protocol: TCP
            - name: stun
              containerPort: 3478
              protocol: UDP
            - name: syslog
              containerPort: 5514
              protocol: UDP
            - name: discovery
              containerPort: 10001
              protocol: UDP
            - name: l2-discovery
              containerPort: 1900
              protocol: UDP
          startupProbe:
            httpGet:
              port: web-admin
            failureThreshold: 30    # 10s x 30 = 5min
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: web-admin
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: web-admin
            initialDelaySeconds: 15
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: "/config"
              name: unifi-data
      volumes:
        - name: unifi-data
          persistentVolumeClaim:
            claimName: unifi-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data-pvc
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: Service
metadata:
    name: unifi-controller-tcp
    namespace: unifi
    annotations:
        metallb.universe.tf/allow-shared-ip: "unifi-controller-svc"
    labels:
      app: unifi-controller
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.202
    externalTrafficPolicy: Local
    ports:
      - name: dns
        protocol: TCP
        port: 53
        targetPort: dns
      - name: web-admin
        protocol: TCP
        port: 8443
        targetPort: web-admin
      - name: api
        protocol: TCP
        port: 8080
        targetPort: api
      - name: guest-https
        protocol: TCP
        port: 8843
        targetPort: guest-https
      - name: guest-http
        protocol: TCP
        port: 8880
        targetPort: guest-http
      - name: speed-test
        protocol: TCP
        port: 6789
        targetPort: speed-test
    selector:
        app: unifi-controller
---
apiVersion: v1
kind: Service
metadata:
    name: unifi-controller-udp
    namespace: unifi
    annotations:
        metallb.universe.tf/allow-shared-ip: "unifi-controller-svc"
    labels:
      app: unifi-controller
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.202
  externalTrafficPolicy: Local
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: dns
    - name: stun
      protocol: UDP
      port: 3478
      targetPort: stun
    - name: syslog
      protocol: UDP
      port: 5514
      targetPort: syslog
    - name: discovery
      protocol: UDP
      port: 10001
      targetPort: discovery
    - name: l2-discovery
      protocol: UDP
      port: 1900
      targetPort: l2-discovery
  selector:
    app: unifi-controller